name: flashy
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  responsive_sizer: ^3.3.1
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  easy_localization: ^3.0.7
  flutter_lints: ^3.0.0
  get_it: ^7.6.4
  package_info_plus: ^8.0.2
  dots_indicator: ^3.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^5.0.0
  dynamic_height_grid_view: ^0.0.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  connectivity_plus: ^5.0.1
  flutter_bloc: ^8.1.3




flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.otf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700


  